FROM golang:latest

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY Makefile ./

COPY go.mod go.sum ./
RUN go mod download

COPY static/ /app/static/
COPY . /app

CMD ["air", "-c", ".air.toml"]
