FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
RUN python3 manage.py check --deploy
EXPOSE 8000
CMD python manage.py makemigrations auth_webapp && python manage.py migrate && python manage.py runserver 0.0.0.0:8000

