# Generated by Django 3.2.2 on 2021-05-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSUUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('shib_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name_num', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('discord_id', models.CharField(max_length=100, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('affiliation', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ALUMNI', 'Alumni'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
