# Generated by Django 3.2.2 on 2021-05-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuuser',
            name='affiliation',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY_STAFF', 'Faculty Staff'), ('ALUMNI', 'Alumni'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
