# Generated by Django 3.2.2 on 2021-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0003_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
