# Generated by Django 3.2.2 on 2021-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0004_alter_attendancerecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='osuuser',
            name='added_to_mailing_list',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
