# Generated by Django 3.2.2 on 2021-08-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0005_osuuser_added_to_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuuser',
            name='added_to_mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
