# Generated by Django 3.2.2 on 2021-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0006_alter_osuuser_added_to_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
