# Generated by Django 3.2.2 on 2022-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_webapp', '0008_osuuser_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attend_type',
            field=models.CharField(choices=[('IN_PERSON', 'In Person'), ('ONLINE', 'Online'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=20),
        ),
    ]
