
name: Docker
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env
        run: |
          touch .env
          mkdir keys
          touch keys/sp-cert.pem
          touch keys/sp-key.pem

      - name: Build image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            .
